# -*- coding: utf-8 -*-
"""Mile Stone 1 - Infosys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fE67bf3v7CARw5KQDyfNSFnSF6UODzd

**Cell 1 — Install & imports**
"""

!pip -q install sentence-transformers scikit-learn matplotlib

import ast, io, tokenize, textwrap, math, itertools, json, os
from typing import List, Dict, Any
import numpy as np
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import cosine_similarity

"""**Python code snippets**"""

code_snippets = [
    # 1 recursion
    """def factorial(n):
        return 1 if n==0 else n*factorial(n-1)""",

    # 2 fibonacci loop
    """def fibonacci(n):
        a,b=0,1
        for _ in range(n):
            a,b=b,a+b
        return a""",

    # 3 class + method
    """class Person:
        def __init__(self,name):
            self.name=name
        def greet(self):
            return f"Hello {self.name}" """,

    # 4 imports
    """import math
print(math.sqrt(16))""",

    # 5 list comprehension + lambda
    """squares = list(map(lambda x:x*x, [1,2,3,4]))""",

    # 6 generator
    """def gen(n):
        for i in range(n):
            yield i*i""",

    # 7 try/except
    """def safe_div(a,b):
        try:
            return a/b
        except ZeroDivisionError:
            return None""",

    # 8 decorator
    """def log(f):
        def inner(*args, **kwargs):
            print("calling", f.__name__)
            return f(*args, **kwargs)
        return inner

@log
def add(a,b): return a+b""",

    # 9 with/context manager
    """from contextlib import contextmanager
@contextmanager
def open_upper(path):
    f=open(path,'r')
    try:
        yield f.read().upper()
    finally:
        f.close()""",

    # 10 while + break
    """def find_first_even(nums):
        i=0
        while i<len(nums):
            if nums[i]%2==0:
                return nums[i]
            i+=1
        return None""",

    # 11 set/dict usage
    """def unique_counts(items):
        d={}
        for x in items:
            d[x]=d.get(x,0)+1
        return {k for k,v in d.items() if v==1}""",

    # 12 simple async
    """import asyncio
async def hello():
    await asyncio.sleep(0)
    return "hi" """
]

# Clean indentation (helpful if you edit snippets)
code_snippets = [textwrap.dedent(s).strip() for s in code_snippets]
len(code_snippets)

"""**AST parsing utilities**"""

def analyze_ast(code: str) -> Dict[str, Any]:
    tree = ast.parse(code)
    functions, classes, imports, from_imports = [], [], [], []
    loops, conditionals, returns, raises = 0,0,0,0
    recursion = False
    called_funcs = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            functions.append(node.name)
        elif isinstance(node, ast.ClassDef):
            classes.append(node.name)
        elif isinstance(node, ast.Import):
            for n in node.names: imports.append(n.name)
        elif isinstance(node, ast.ImportFrom):
            mod = node.module if node.module else ""
            for n in node.names: from_imports.append(f"{mod}.{n.name}".strip("."))
        elif isinstance(node, (ast.For, ast.While)):
            loops += 1
        elif isinstance(node, ast.If):
            conditionals += 1
        elif isinstance(node, ast.Return):
            returns += 1
        elif isinstance(node, ast.Raise):
            raises += 1
        elif isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name):
                called_funcs.add(node.func.id)

    # simple recursion check: any function calls itself
    recursion = any(fn in called_funcs for fn in functions)

    return {
        "functions": functions,
        "classes": classes,
        "imports": imports,
        "from_imports": from_imports,
        "loops": loops,
        "ifs": conditionals,
        "returns": returns,
        "raises": raises,
        "recursion": recursion,
    }

ast_reports = [analyze_ast(c) for c in code_snippets]
for i, r in enumerate(ast_reports, 1):
    print(f"Snippet {i}: {r}")

"""**Tokenization**"""

def tokenize_code(code: str) -> Dict[str, Any]:
    toks = []
    counts = {}
    for tok in tokenize.generate_tokens(io.StringIO(code).readline):
        toks.append(tok.string)
        counts[tok.type] = counts.get(tok.type, 0) + 1
    joined = " ".join([t for t in toks if t.strip()])
    return {"tokens": toks, "joined": joined, "count": len(toks), "types": counts}

token_reports = [tokenize_code(c) for c in code_snippets]
for i, r in enumerate(token_reports, 1):
    print(f"Snippet {i}: token_count={r['count']}")

"""**Embeddings** **with** **three** **models**


"""

model_names = {
    "MiniLM": "sentence-transformers/all-MiniLM-L6-v2",
    "DistilRoBERTa": "sentence-transformers/paraphrase-distilroberta-base-v2",
    "MPNet": "sentence-transformers/all-mpnet-base-v2",
}

# You can choose whether to feed raw code or token-joined text; we'll use raw code.
embeddings = {}
for label, name in model_names.items():
    print("Loading:", label, name)
    model = SentenceTransformer(name)
    emb = model.encode(code_snippets, convert_to_numpy=True, normalize_embeddings=True)
    embeddings[label] = emb

{ k: v.shape for k,v in embeddings.items() }

"""**Similarity** **matrices**"""

def cosim_matrix(E: np.ndarray) -> np.ndarray:
    return cosine_similarity(E)

sims = {k: cosim_matrix(v) for k, v in embeddings.items()}

for k, M in sims.items():
    print(f"{k} similarity matrix shape: {M.shape}")

"""**PCA**"""

def pca_plot(E: np.ndarray, title: str):
    p = PCA(n_components=2).fit_transform(E)
    plt.figure()
    plt.scatter(p[:,0], p[:,1])
    for i, (x,y) in enumerate(p):
        plt.annotate(str(i+1), (x, y))
    plt.title(title)
    plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.show()

for label, E in embeddings.items():
    pca_plot(E, f"PCA — {label}")

"""**Heatmap of cosine similarities (per model)**"""

def heatmap(M: np.ndarray, title: str):
    plt.figure()
    plt.imshow(M, interpolation='nearest')
    plt.title(title)
    plt.colorbar()
    plt.xlabel("Snippet"); plt.ylabel("Snippet")
    plt.xticks(range(1, len(M)+1), range(1, len(M)+1))
    plt.yticks(range(1, len(M)+1), range(1, len(M)+1))
    plt.show()

for label, M in sims.items():
    heatmap(M, f"Cosine Similarity — {label}")

"""**Cross** -**model** **comparison**"""

def upper_tri_flat(M: np.ndarray) -> np.ndarray:
    n = M.shape[0]
    idx = np.triu_indices(n, k=1)
    return M[idx]

labels = list(sims.keys())
comparisons = []
for a, b in itertools.combinations(labels, 2):
    va, vb = upper_tri_flat(sims[a]), upper_tri_flat(sims[b])
    pear = np.corrcoef(va, vb)[0,1]
    comparisons.append((a, b, float(pear)))

print("Pearson correlation between similarity matrices:")
for a,b,r in comparisons:
    print(f"{a} vs {b}: {r:.3f}")

"""**Tabular** **summary**"""

import pandas as pd

rows = []
for i, (code, ast_r, tok_r) in enumerate(zip(code_snippets, ast_reports, token_reports), 1):
    rows.append({
        "id": i,
        "len_chars": len(code),
        "len_lines": len(code.splitlines()),
        "tokens": tok_r["count"],
        "functions": ",".join(ast_r["functions"]),
        "classes": ",".join(ast_r["classes"]),
        "imports": ",".join(ast_r["imports"] + ast_r["from_imports"]),
        "loops": ast_r["loops"],
        "ifs": ast_r["ifs"],
        "returns": ast_r["returns"],
        "raises": ast_r["raises"],
        "recursion": ast_r["recursion"],
    })
df_summary = pd.DataFrame(rows)

from google.colab import data_table
data_table.enable_dataframe_formatter()
df_summary
